---

- name: Create Gemini DB (mysql)
  mysql_db:
    name: "{{ crayfish_db_name }}"
    login_host: "{{ crayfish_db_host }}"
    login_port: "{{ crayfish_db_port }}"
    login_user: "{{ crayfish_db_root_user }}"
    login_password:  "{{ crayfish_db_root_password }}"
    state: present
  register: gemini_db_exists

- name: Create Gemini DB User (mysql)
  mysql_user:
    name: "{{ crayfish_db_user }}"
    password: "{{ crayfish_db_password }}"
    login_host: "{{ crayfish_db_host }}"
    login_port: "{{ crayfish_db_port }}"
    login_user: "{{ crayfish_db_root_user }}"
    login_password:  "{{ crayfish_db_root_password }}"
    state: present
    priv: "{{crayfish_db_name}}.*:ALL"
    host: "%"

