---

- name: Create Gemini DB User (pgsql)
  postgresql_user:
    name: "{{ crayfish_db_user }}"
    password: "{{ crayfish_db_password }}"
    login_host: "{{ crayfish_db_host }}"
    login_port: "{{ crayfish_db_port }}"
    login_user: "{{ crayfish_db_root_user }}"
    login_password:  "{{ crayfish_db_root_password }}"

- name: Create Gemini DB (pgsql)
  postgresql_db:
    name: "{{ crayfish_db_name }}"
    state: present
    owner: "{{ crayfish_db_user }}"
    login_host: "{{ crayfish_db_host }}"
    login_port: "{{ crayfish_db_port }}"
    login_user: "{{ crayfish_db_root_user }}"
    login_password:  "{{ crayfish_db_root_password }}"
  register: gemini_db_exists
