---

- name: Install build packages (Yum)
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - automake
    - autoconf
    - libtool
    - zlib-devel
    - libjpeg-devel
    - giflib
    - libtiff-devel
    - libwebp
    - libwebp-devel
    - libicu-devel
    - openjpeg-devel
    - cairo-devel
    - openjpeg2-devel

- name: Unarchive Leptonica
  unarchive:
    remote_src: yes
    src: "http://www.leptonica.com/source/leptonica-{{ leptonica_version }}.tar.gz"
    dest: "/opt/"

- name: Config Leptonica
  command: ./configure
  args:
    chdir: "{{ leptonica_build }}"
  become: true

- name: Make Leptonica
  command: make
  args:
    chdir: "{{ leptonica_build }}"
  become: true

- name: Install Leptonica
  command: make install
  args:
    chdir: "{{ leptonica_build }}"
  become: true

- name: Clone Tesseract
  git:
    repo: https://github.com/tesseract-ocr/tesseract.git
    dest: "{{ tesseract_directory }}"
    version: "{{ tesseract_version }}"

- name: Tesseract build directory
  file:
    path: "{{ tesseract_directory }}/build"
    state: directory

- name: Autogen Tesseract
  command: "./autogen.sh"
  args:
    chdir: "{{ tesseract_directory }}"
  become: true

- name: Configure Tesseract
  command: "./configure"
  args:
    chdir: "{{ tesseract_directory }}"
  become: true
  environment:
    PKG_CONFIG_PATH: /usr/local/lib/pkgconfig
  register: tconfig

- name: Make Tesseract
  command: make
  args:
    chdir: "{{ tesseract_directory }}"
  become: true

- name: Install Tesseract
  command: make install
  args:
    chdir: "{{ tesseract_directory }}"
  become: true

- name: Download Tesseract language packs
  get_url:
    url: "https://github.com/tesseract-ocr/tessdata/raw/{{ tesseract_lang_version }}/{{ item }}.traineddata"
    dest: "{{ tesseract_lang_dir }}"
  with_items:
    - eng
    - deu
    - fra
    - ita
